created the component
contacto-io/style-guide pull request #33
Opened 2022-10-26 13:40 UTC by rishabhPlivo

2022-10-26 16:40 UTC, samuellawrentz commented on src/components/GroupAndSearchDropdown/index.js
> +          <TextField type="search-box" placeholder="Search" onChange={onSearchChange} />
How is the value cleared?
i.e what happens when you close and open the dropdown? Is the `searchValue` retained?

2022-10-27 03:38 UTC, samuellawerentz requested changes

2022-10-27 03:38 UTC, samuellawerentz commented on src/components/GroupAndSearchDropdown/GroupAndSearchDropdown.stories.js
> +      children: ['Abcd', 'efgh', 'erekug', 'fhjdkg'],
We should be having an object, which has `label` and `value`.

2022-10-27 03:38 UTC, samuellawerentz commented on src/components/GroupAndSearchDropdown/groupAndSearchDropdown.scss
> +  z-index: 1000;
We can make this 10. `1000` seems too much.

2022-10-27 03:38 UTC, samuellawerentz commented on src/components/GroupAndSearchDropdown/index.js
> +export const GroupAndSearchDropdown = ({ options, onSearchChange, className, ...props }) => {
`onSearchChange` could be an internal function.

2022-10-27 03:38 UTC, samuellawerentz commented on src/components/GroupAndSearchDropdown/index.js
> +                  setValue(child)
on selection, we should append the selected value to the existing value. We should not clear it.

2022-10-27 08:24 UTC, merged