Feature/cnto 7519/email channel
contacto-io/style-guide pull request #71
Opened 2023-12-12 06:11 UTC by malay2

2023-12-12 06:50 UTC, samuellawerentz commented
@CodiumAI-Agent /review

2023-12-12 06:51 UTC, samuellawerentz requested changes

2023-12-12 06:51 UTC, samuellawerentz commented on src/components/GroupAndSearchDropdown/groupAndSearchDropdown.scss
> +    border-bottom: 0.5px solid #e6e7ea;
Use variable here.

2023-12-12 06:51 UTC, CodiumAI-Agent commented
## PR Analysis

- 🎯 **Main theme:** This PR introduces tags support in Select and makes the dropdown visible in GroupAndSearchDropdown.
- 📝 **PR summary:** The PR adds tags support in Select and modifies the GroupAndSearchDropdown to only show the dropdown and not the text field. It also includes changes to the storybook files to reflect these changes and some CSS adjustments.
- 📌 **Type of PR:** Enhancement
- 🧪 **Relevant tests added:** No
- ⏱️ **Estimated effort to review [1-5]:** 3, because the PR involves changes in multiple files and introduces new features which need to be reviewed carefully.
- 🔒 **Security concerns:** No security concerns found
## PR Feedback

- 💡 **General suggestions:** The PR is well-structured and the changes are clear. However, it would be beneficial to add tests to ensure the new features work as expected. Also, it's a good practice to avoid using console.log in production code. Instead, consider using a proper logging library or remove it if it's only for debugging purposes.


- <details><summary> 🤖 Code feedback:</summary>


  - **relevant file:** ``src/components/GroupAndSearchDropdown/index.js``  
   **suggestion:** Consider using a more descriptive name for the `onlyDropdown` prop. It's not immediately clear what it does. A more descriptive name could be `showOnlyDropdown`. [medium]  
   **relevant line:** [onlyDropdown,](https://github.com/contacto-io/style-guide/pull/71/files#diff-a1dd843e0f1c7b8aabef690140c196a31b14ffaccd8038f03daec986f84ad475R29)  


  - **relevant file:** ``src/components/GroupAndSearchDropdown/index.js``  
   **suggestion:** Avoid using direct DOM manipulation like `setSelectionRange`. It's not recommended in React as it can lead to unpredictable behavior. Try to achieve the same functionality using React state. [important]  
   **relevant line:** [setTimeout(() => e.target.setSelectionRange?.(caretStart, caretEnd), 0)](https://github.com/contacto-io/style-guide/pull/71/files#diff-a1dd843e0f1c7b8aabef690140c196a31b14ffaccd8038f03daec986f84ad475R159)  


  - **relevant file:** ``src/components/Select/index.js``  
   **suggestion:** It's a good practice to provide default values for props. Consider providing a default value for the `mode` prop. [medium]  
   **relevant line:** [mode: PropTypes.oneOf(['multiple', 'tags']),](https://github.com/contacto-io/style-guide/pull/71/files#diff-c597af606d68d09e40081d5289a44d844b0fe318586e4a2241f8392c21d9f7b5R219)  


  - **relevant file:** ``src/components/GroupAndSearchDropdown/index.js``  
   **suggestion:** Avoid using `any` as a type. It defeats the purpose of using PropTypes for type checking. Consider replacing `PropTypes.any` with a more specific type. [important]  
   **relevant line:** [parentTextFieldRef: PropTypes.any,](https://github.com/contacto-io/style-guide/pull/71/files#diff-a1dd843e0f1c7b8aabef690140c196a31b14ffaccd8038f03daec986f84ad475R183)  

</details>


### How to use

 <details> <summary> Instructions</summary>

> Tag me in a comment '@CodiumAI-Agent' and add one of the following commands:  
> **/review**: Request a review of your Pull Request.   
> **/describe**: Update the PR title and description based on the contents of the PR.   
> **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> **/ask \<QUESTION\>**: Ask a question about the PR.   
> **/update_changelog**: Update the changelog based on the PR's contents.   
> **/add_docs**: Generate docstring for new components introduced in the PR.   
> **/generate_labels**: Generate labels for the PR based on the PR's contents.   
> see the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.

>To edit any configuration parameter from the [configuration.toml](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml), add --config_path=new_value.  
>For example: /review --pr_reviewer.extra_instructions="focus on the file: ..."    
>To list the possible configuration parameters, add a **/config** comment.   

</details>

2023-12-12 06:52 UTC, samuellawerentz commented
@CodiumAI-Agent /improve

2023-12-12 06:53 UTC, CodiumAI-Agent commented on src/components/GroupAndSearchDropdown/index.js
>    )
**Suggestion:** Extract the logic for handling the dropdown and text field into a separate function to improve readability and maintainability.
```suggestion
        {renderTextField()}

        // Add this function above the return statement
        function renderTextField() {
          if (onlyDropdown) {
            return <div></div>;
          }

          const handleKeyUp = (e) => {
            e.persist();
            const value = e.target.value;
            const caretEnd = e.target.selectionEnd;
            const keyPressed = value[caretEnd - 1];
            const openDropdown =
              value.slice(-2) === '{{' ||
              (keyPressed === '|' && /\{\{[\w|]+\|$/g.test(value.substring(0, caretEnd)));
            setShowDropdown(openDropdown);
          };

          const handleChange = (e) => {
            e.persist();
            const caretStart = e.target.selectionStart;
            const caretEnd = e.target.selectionEnd;
            onChange(e);
            setTimeout(() => e.target.setSelectionRange?.(caretStart, caretEnd), 0);
          };

          return (
            <div className={`group-dropdown`}>
              <TextField
                type={'text'}
                ref={textFieldRef}
                suffix={
                  <div
                    onClick={(e) => {
                      e.stopPropagation();
                      setShowDropdown(!showDropdown);
                    }}
                    className="contacto-icon--input-suffix-variable-dropdown"
                  >
                    <Icon svg={dropdownIcon} size={20} />
                  </div>
                }
                onClick={(e) => !openOnTextboxClick && e.stopPropagation()}
                onKeyUp={handleKeyUp}
                onChange={handleChange}
                {...props}
              />
            </div>
          );
        }
```

2024-01-04 16:34 UTC, samuellawerentz approved these changes

2024-02-20 12:29 UTC, rishabhPlivo commented on src/components/GroupAndSearchDropdown/index.js
> +  const [showDropdown, setShowDropdown] = useState(onlyDropdown)
do we need a default value for onlyDropdown?

2024-02-20 12:29 UTC, rishabhPlivo commented on src/components/GroupAndSearchDropdown/index.js
> +                    if (onlyDropdown && parentTextFieldRef) parentTextFieldRef.current?.focus()
Can we move this to a method?

2024-02-20 12:29 UTC, rishabhPlivo commented on src/components/GroupAndSearchDropdown/index.js
> +          <div></div>
can we invert the condition and return null in else case?

2024-03-19 11:28 UTC, merged